# Generated by Django 5.1.6 on 2025-04-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='aadhar',
            old_name='lname',
            new_name='last_name',
        ),
    ]
