# Generated by Django 5.1.5 on 2025-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aadhar_adhar_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='pan',
            field=models.CharField(default='ASDFGH0987H', max_length=10),
        ),
    ]
