# Generated by Django 5.1.5 on 2025-04-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_aadhar_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='adhar_num',
        ),
        migrations.AddField(
            model_name='aadhar',
            name='aadhar_num',
            field=models.BigAutoField(default=123456789012, primary_key=True, serialize=False),
        ),
    ]
