# Generated by Django 5.1.5 on 2025-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_aadhar_adhar_num_aadhar_aadhar_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_num',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
